name: IML3.6
channels:
  - defaults
dependencies:
  - pip=20.2.2
  - python=3.6.12
  - pip:
    - arff==0.9
    - matplotlib==3.3.2
    - numpy==1.19.2
    - pandas==1.1.2
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - seaborn==0.11.0
    - sklearn==0.0
